/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/search/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Papers Json
         * @description JSON endpoint for searching literature.
         *
         *     source param:
         *     - "europepmc" = Europe PMC only (default)
         *     - "openalex" = OpenAlex only
         */
        post: operations["search_papers_json_search_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article Types
         * @description Get available article types for a search source.
         *
         *     - source="openalex": Returns OpenAlex work types with live counts
         *     - source="europepmc": Returns Europe PMC publication types
         */
        get: operations["get_article_types_search_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse Paper Json
         * @description JSON endpoint for fetching paper data with identifier-aware fallback.
         *
         *     Highlighting priority:
         *       1. NER in-memory / ner_cache hit  → entities highlighted at NER-run time
         *       2. run_ner=True                   → live NER, result cached
         *       3. paper_entities DB table        → pre-extracted entities used to highlight
         *          HTML so the entity-index <> navigation finds real DOM nodes
         *
         *     If source="openalex", skip Europe PMC fallback - only return OpenAlex metadata.
         */
        post: operations["analyse_paper_json_paper_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/section/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Section Json
         * @description JSON endpoint for switching sections.
         */
        post: operations["switch_section_json_paper_section_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Paper Pdf
         * @description Resolve and stream a paper PDF when one is available.
         */
        get: operations["download_paper_pdf_paper_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/pdf-proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proxy Pdf
         * @description Proxy PDF download from an allowed scholarly URL (bypasses CORS).
         */
        get: operations["proxy_pdf_paper_pdf_proxy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/db/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Papers
         * @description Fetch a paginated list of papers from the local SQLite database.
         */
        get: operations["list_papers_paper_db_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/db/{doi}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper Entities
         * @description Fetch pre-extracted entities for a paper from the SQLite database
         *     using its DOI.
         *
         *     Returns ``{label, text, canonical, count, metadata, aliases}`` per
         *     entity. ``metadata`` is whatever was stored in the ``paper_entities.
         *     metadata`` JSON column at ingest time (chemical/species enrichment
         *     happens on the frontend via the gazetteer CSVs at render time).
         */
        get: operations["get_paper_entities_paper_db__doi__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ner/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Text Ner
         * @description Standalone NER endpoint: takes raw text or sections, returns extracted entities.
         *     Can be used on any text, not just papers.
         *
         *     Request body option 1 (plain text):
         *     {
         *         "text": "raw text to extract entities from"
         *     }
         *
         *     Request body option 2 (sections - better for papers):
         *     {
         *         "sections": [
         *             {"title": "Abstract", "content": "..."},
         *             {"title": "Methods", "content": "..."}
         *         ]
         *     }
         *
         *     Response:
         *     {
         *         "summary": { ... },
         *         "entities": [ ... ]
         *     }
         */
        post: operations["process_text_ner_ner_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ner/doi/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Doi Json */
        post: operations["process_doi_json_ner_doi_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ner/cache/{doi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Ner Cache
         * @description Clear NER cache for a specific DOI (both disk cache and in-memory).
         */
        delete: operations["clear_ner_cache_ner_cache__doi__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ner/upload/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Pdf For Ner
         * @description Upload PDF for NER extraction.
         *
         *     1. Extracts metadata (title, DOI)
         *     2. Extracts full text
         *     3. Runs the full NER pipeline (dictionary + LLM, same as the paper viewer)
         *     4. Returns metadata + entities + stored PDF URL
         */
        post: operations["upload_pdf_for_ner_ner_upload_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ner/uploaded/{stored_filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View Uploaded Pdf */
        get: operations["view_uploaded_pdf_ner_uploaded__stored_filename__get"];
        put?: never;
        post?: never;
        /**
         * Delete Uploaded Pdf
         * @description Delete an uploaded PDF and its metadata.
         */
        delete: operations["delete_uploaded_pdf_ner_uploaded__stored_filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/upload/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Pdfs Json
         * @description Upload PDFs for indexing. Returns immediately; processing continues in background.
         *
         *     Args:
         *         parser_type: "pymupdf" for fast extraction, "docling" for detailed
         */
        post: operations["upload_pdfs_json_api_chat_upload_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/upload/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload Status
         * @description Get the status of an async upload job.
         */
        get: operations["get_upload_status_api_chat_upload_status__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/upload/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Upload Jobs
         * @description List active upload jobs for the current user only.
         */
        get: operations["list_upload_jobs_api_chat_upload_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/files/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Indexed Files
         * @description List all documents currently indexed in the RAG vector store for the user.
         */
        get: operations["list_indexed_files_api_chat_files_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/files/{filename}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Uploaded File Content
         * @description Return the uploaded PDF file for inline viewing for the current user.
         */
        get: operations["get_uploaded_file_content_api_chat_files__filename__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/files/{filename}/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Uploaded File Markdown
         * @description Return the extracted markdown view of an uploaded paper.
         *
         *     The citation preview panel calls this to render the paper with the
         *     cited chunk highlighted. The markdown is normally written to disk
         *     at ingest time. For papers ingested before this feature shipped,
         *     we lazy-regenerate via plain PyMuPDF on first request — pure
         *     side-effect; the next request hits the cached file.
         *
         *     Response shape: ``{"markdown": "<utf-8 text>"}``.
         */
        get: operations["get_uploaded_file_markdown_api_chat_files__filename__markdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description Remove a source completely: chunks from ChromaDB.
         */
        delete: operations["delete_source_api_chat_files__filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Rag Data
         * @description Permanently delete all indexed chunks for the user.
         */
        post: operations["reset_rag_data_api_chat_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup User Data
         * @description Clean up all data for a user when they close their browser.
         *     Deletes: ChromaDB, uploads, and all user files.
         */
        post: operations["cleanup_user_data_api_chat_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/query/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Rag Json */
        post: operations["query_rag_json_api_chat_query_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Rag Stream
         * @description Streaming RAG query — returns NDJSON frames as the LLM produces
         *     them. The frontend's runtime adapter consumes this via fetch's
         *     streaming body and yields text deltas to assistant-ui.
         *
         *     One JSON object per line. Frame types:
         *       * ``{"type":"text_delta","text":"..."}`` — additive token
         *       * ``{"type":"sources","sources":[...]}``  — citation list
         *       * ``{"type":"error","error":"..."}``      — fatal mid-stream
         *       * ``{"type":"done"}``                     — clean end of stream
         */
        post: operations["query_rag_stream_api_chat_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Followups
         * @description Return short follow-up question suggestions based on the recent
         *     conversation. Used by assistant-ui's SuggestionAdapter to populate
         *     "you might also ask…" chips. Always returns 200 with a (possibly
         *     empty) list — suggestions are best-effort and never fatal.
         */
        post: operations["suggest_followups_api_chat_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Readiness for load balancers. Statuses: ready | degraded | down.
         *
         *     - llm: config-only `llm_status()` plus a cached non-billable `/models`
         *       dial (`chat/ai/health.py`). Unconfigured/misconfigured keys were
         *       previously 200/"partial" — now "degraded" so dashboards notice.
         *     - qdrant: probed only after the RAG service boots; before that it is
         *       "deferred" (counts as degraded, not ready-green).
         *     Only "down" (Qdrant error) returns 503.
         */
        get: operations["readiness_check_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doi/abstract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Doi Abstract
         * @description Fetch abstract for a DOI when Europe PMC doesn't have it.
         *     Uses DOI-oriented fallback: OpenAlex → Semantic Scholar.
         *     Results are cached for future requests.
         */
        get: operations["get_doi_abstract_doi_abstract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Metrics
         * @description Aggregated metrics for the homepage dashboard.
         */
        get: operations["get_dashboard_metrics_api_dashboard_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Spa
         * @description Serve the React SPA for all non-API routes.
         */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyse_paper_json_paper_json_post */
        Body_analyse_paper_json_paper_json_post: {
            /** Doi */
            doi: string;
            /**
             * Run Ner
             * @default false
             */
            run_ner: boolean;
            /**
             * Source
             * @default
             */
            source: string;
        };
        /** Body_search_papers_json_search_json_post */
        Body_search_papers_json_search_json_post: {
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Open Access
             * @default false
             */
            open_access: boolean;
            /**
             * Has Full Text
             * @default false
             */
            has_full_text: boolean;
            /**
             * Article Type
             * @default
             */
            article_type: string;
            /**
             * Sort
             * @default
             */
            sort: string;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Cursor Mark
             * @default *
             */
            cursor_mark: string;
            /**
             * Source
             * @default europepmc
             */
            source: string;
        };
        /** Body_switch_section_json_paper_section_json_post */
        Body_switch_section_json_paper_section_json_post: {
            /** Doi */
            doi: string;
            /** Section Idx */
            section_idx: number;
        };
        /** Body_upload_pdf_for_ner_ner_upload_json_post */
        Body_upload_pdf_for_ner_ner_upload_json_post: {
            /** File */
            file: string;
        };
        /** Body_upload_pdfs_json_api_chat_upload_json_post */
        Body_upload_pdfs_json_api_chat_upload_json_post: {
            /** Files */
            files: string[];
            /**
             * Parser Type
             * @default pymupdf
             */
            parser_type: string | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** Entity */
        Entity: {
            /** Text */
            text: string;
            /** Label */
            label: string;
            /** Score */
            score: number;
            /** Canonical */
            canonical?: string | null;
            /** Preferred Name */
            preferred_name?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Name Type */
            name_type?: string | null;
            /** Linked To */
            linked_to?: string | null;
            /** Scientific Name Verified */
            scientific_name_verified?: string | null;
            /** Accepted Scientific Name */
            accepted_scientific_name?: string | null;
            /** Common Name */
            common_name?: string | null;
            /** Inchikey */
            inchikey?: string | null;
            /** Smiles */
            smiles?: string | null;
            /** Molecular Formula */
            molecular_formula?: string | null;
            /** Source Db */
            source_db?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Taxon Id */
            taxon_id?: string | null;
            /** Match Status */
            match_status?: string | null;
            /** Review Required */
            review_required?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexedFileInfo */
        IndexedFileInfo: {
            /** Name */
            name: string;
            /** File Type */
            file_type: string;
            /** Chunk Count */
            chunk_count: number;
            /** Indexed At */
            indexed_at: string;
            /** Parser Type */
            parser_type: string;
            /** Authors */
            authors?: string | null;
            /** Doi */
            doi?: string | null;
            /** Journal */
            journal?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** NERRequest */
        NERRequest: {
            /** Doi */
            doi: string;
        };
        /** NERResponse */
        NERResponse: {
            /** Doi */
            doi: string;
            /** Mode */
            mode: string;
            /** Text */
            text: string;
            /** Entities */
            entities: components["schemas"]["Entity"][];
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /** Selected Files */
            selected_files?: string[] | null;
            /** Chat History */
            chat_history?: components["schemas"]["ChatMessage"][] | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
        };
        /**
         * SuggestRequest
         * @description Body for /api/chat/suggest. Mirrors the recent slice of the
         *     conversation that the assistant-ui SuggestionAdapter sends.
         */
        SuggestRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** SuggestResponse */
        SuggestResponse: {
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionItem"][];
        };
        /** SuggestionItem */
        SuggestionItem: {
            /** Prompt */
            prompt: string;
        };
        /** UploadJobStatus */
        UploadJobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Files */
            files: string[];
            /** Parser Type */
            parser_type: string;
            /** Summaries */
            summaries?: {
                [key: string]: string;
            } | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Files */
            files: string[];
            /** Summaries */
            summaries?: {
                [key: string]: string;
            } | null;
            /** Job Id */
            job_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_papers_json_search_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_search_papers_json_search_json_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_types_search_types_get: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_paper_json_paper_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_analyse_paper_json_paper_json_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_section_json_paper_section_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_switch_section_json_paper_section_json_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_paper_pdf_paper_pdf_get: {
        parameters: {
            query: {
                identifier: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_pdf_paper_pdf_proxy_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_papers_paper_db_list_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                country?: string;
                query?: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_entities_paper_db__doi__entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_text_ner_ner_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_doi_json_ner_doi_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NERRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NERResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_ner_cache_ner_cache__doi__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_pdf_for_ner_ner_upload_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pdf_for_ner_ner_upload_json_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    view_uploaded_pdf_ner_uploaded__stored_filename__get: {
        parameters: {
            query: {
                expires: number;
                token: string;
            };
            header?: never;
            path: {
                stored_filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_uploaded_pdf_ner_uploaded__stored_filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stored_filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_pdfs_json_api_chat_upload_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pdfs_json_api_chat_upload_json_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_status_api_chat_upload_status__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upload_jobs_api_chat_upload_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_indexed_files_api_chat_files_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexedFileInfo"][];
                };
            };
        };
    };
    get_uploaded_file_content_api_chat_files__filename__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_uploaded_file_markdown_api_chat_files__filename__markdown_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_chat_files__filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_rag_data_api_chat_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cleanup_user_data_api_chat_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    query_rag_json_api_chat_query_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_rag_stream_api_chat_query_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_followups_api_chat_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readiness_check_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_doi_abstract_doi_abstract_get: {
        parameters: {
            query: {
                /** @description DOI to fetch abstract for */
                doi: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_metrics_api_dashboard_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
