/**
 * assistant-ui ChatModelAdapter for the PhytoQuery RAG backend.
 *
 * Bridges assistant-ui's thread state to our FastAPI RAG endpoints:
 *   - Maps assistant-ui ThreadMessage[] -> our { role, content } chat_history
 *   - Sends `selected_files` derived from current React state via a
 *     getter callback (so the adapter never captures a stale selection)
 *   - Calls `fetch` directly with the runtime-supplied AbortSignal so
 *     the user's Cancel button immediately terminates the in-flight
 *     request — both for streaming and non-streaming paths
 *   - Streams the answer via /api/chat/query/stream (NDJSON: text
 *     deltas and a final sources frame). Returns an AsyncGenerator so
 *     assistant-ui paints the answer progressively as tokens arrive.
 *   - Falls back to /api/chat/query/json if the streaming endpoint is
 *     unavailable (404) or fails before any tokens arrive.
 *   - Stashes returned sources on the message metadata so a custom
 *     React slot can render the source-pill row under the answer.
 *   - Wires WebSpeechSynthesisAdapter so ActionBar.Speak reads the
 *     answer aloud via the browser's built-in TTS.
 *   - Wires a SuggestionAdapter that hits /api/chat/suggest after each
 *     turn so the empty/idle state can show "you might also ask…"
 *     follow-ups generated by the same LLM.
 */

import type {
  ChatModelAdapter,
  ChatModelRunResult,
  ThreadHistoryAdapter,
  ThreadMessage,
  ThreadMessageLike,
} from '@assistant-ui/react';
import { useLocalRuntime, WebSpeechSynthesisAdapter } from '@assistant-ui/react';
import { useMemo, useRef } from 'react';

const HISTORY_STORAGE_KEY = 'pq_chat_history';

/** Source attribution as our backend returns it. ``chunk_id`` is the
 * per-turn positional id (``c1``, ``c2``, …) the LLM emits inline
 * and the frontend maps to a 1-based superscript number on render.
 *
 * ``body_start``/``body_end`` are char offsets into the saved paper
 * markdown, recorded at ingest time. When present, the citation
 * preview panel slices the markdown directly for byte-exact
 * highlighting; when absent (legacy chunks or ingest substring
 * search failed), the panel falls back to fuzzy matching. ``page``
 * is the 1-based PDF page the chunk starts on, also from ingest. */
export interface RagSource {
  chunk_id?: string;
  source: string;
  section: string;
  parser_type: string;
  score: number;
  chunk_text: string;
  body_start?: number;
  body_end?: number;
  page?: number;
}

/** One verbatim quote backing one claim, returned by Pass 2 of the
 * citation pipeline. The frontend uses ``quote`` to highlight the
 * exact span inside the chunk in the markdown preview panel. */
export interface Citation {
  chunk_id: string;
  quote: string;
}

/** Custom metadata key our messages carry so the UI can render
 * sources, citations, and link superscripts to chunks. */
export interface RagMessageCustomData {
  sources?: RagSource[];
  citations?: Citation[];
}

function extractMessageText(message: ThreadMessage): string {
  if (!message.content) return '';
  return message.content
    .map((part) => (part.type === 'text' ? part.text : ''))
    .join('')
    .trim();
}

function toBackendChatHistory(
  messages: readonly ThreadMessage[],
): Array<{ role: 'user' | 'assistant'; content: string }> {
  // Drop the trailing user message — our backend takes the current
  // question separately as `query`, with prior turns as chat_history.
  // assistant-ui passes ALL messages including the new user one, so we
  // strip the final user turn before sending.
  const trimmed = [...messages];
  if (trimmed.length > 0 && trimmed[trimmed.length - 1].role === 'user') {
    trimmed.pop();
  }
  return trimmed
    .map((m) => {
      const role: 'user' | 'assistant' = m.role === 'user' ? 'user' : 'assistant';
      const content = extractMessageText(m);
      return content ? { role, content } : null;
    })
    .filter((entry): entry is { role: 'user' | 'assistant'; content: string } => entry !== null);
}

interface QueryResponseShape {
  answer?: string;
  sources?: RagSource[];
}

async function postQuery(
  question: string,
  selectedFiles: string[],
  chatHistory: Array<{ role: 'user' | 'assistant'; content: string }>,
  signal: AbortSignal,
): Promise<QueryResponseShape> {
  const response = await fetch('/api/chat/query/json', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: question,
      selected_files: selectedFiles.length > 0 ? selectedFiles : undefined,
      chat_history: chatHistory.length > 0 ? chatHistory : undefined,
    }),
    credentials: 'include',
    signal,
  });
  if (!response.ok) {
    const detail = await response.text().catch(() => response.statusText);
    throw new Error(`Query failed (${response.status}): ${detail}`);
  }
  return response.json();
}

/** NDJSON streaming frame. Backend yields one JSON object per line:
 *   - {type:"text_delta", text:"..."}        — additive text token
 *   - {type:"sources", sources:[...]}        — retrieved chunks
 *   - {type:"citations", citations:[...]}    — deterministic per-claim quotes
 *   - {type:"answer_corrected", text:"..."}  — full answer text after
 *                                              reranker-driven citation
 *                                              re-attribution. Replaces
 *                                              the streamed text wholesale;
 *                                              superscript numbering stays
 *                                              stable (frontend numbers by
 *                                              order of appearance) so the
 *                                              user doesn't see a flicker —
 *                                              only the underlying chunk_id
 *                                              link changes.
 *   - {type:"error",   error:"..."}          — fatal error mid-stream
 *   - {type:"done"}                          — clean end of stream
 */
type StreamFrame =
  | { type: 'text_delta'; text: string }
  | { type: 'sources'; sources: RagSource[] }
  | { type: 'citations'; citations: Citation[] }
  | { type: 'answer_corrected'; text: string }
  | { type: 'error'; error: string }
  | { type: 'done' };

/** Async-iterate NDJSON lines from a fetch response body. Splits on
 * `\n` and parses each non-empty chunk as JSON. */
async function* readNdjsonFrames(
  response: Response,
  signal: AbortSignal,
): AsyncGenerator<StreamFrame, void, void> {
  if (!response.body) return;
  const reader = response.body.getReader();
  const decoder = new TextDecoder('utf-8');
  let buffer = '';

  try {
    while (!signal.aborted) {
      const { value, done } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });

      let newlineIdx: number;
      while ((newlineIdx = buffer.indexOf('\n')) !== -1) {
        const line = buffer.slice(0, newlineIdx).trim();
        buffer = buffer.slice(newlineIdx + 1);
        if (!line) continue;
        try {
          const frame = JSON.parse(line) as StreamFrame;
          yield frame;
        } catch (err) {
          console.warn('Skipping malformed NDJSON line:', line, err);
        }
      }
    }

    // Flush trailing buffer (in case server closed without a final \n).
    const trailing = buffer.trim();
    if (trailing) {
      try {
        yield JSON.parse(trailing) as StreamFrame;
      } catch {
        /* ignore */
      }
    }
  } finally {
    try {
      reader.releaseLock();
    } catch {
      /* noop */
    }
  }
}

/** Open the streaming endpoint. Returns the Response for the caller to
 * iterate. Caller is responsible for handling 404 (endpoint not
 * available) and falling back to the JSON path. */
async function openStream(
  question: string,
  selectedFiles: string[],
  chatHistory: Array<{ role: 'user' | 'assistant'; content: string }>,
  signal: AbortSignal,
): Promise<Response> {
  return fetch('/api/chat/query/stream', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/x-ndjson',
    },
    body: JSON.stringify({
      query: question,
      selected_files: selectedFiles.length > 0 ? selectedFiles : undefined,
      chat_history: chatHistory.length > 0 ? chatHistory : undefined,
    }),
    credentials: 'include',
    signal,
  });
}

/** sessionStorage-backed history adapter. Single key — chat history
 * survives a page reload during the same browser session. Cleared via
 * the existing "Reset all" flow (clearPersistedChatHistory). */
function createSessionHistoryAdapter(): ThreadHistoryAdapter {
  return {
    async load() {
      try {
        const raw = sessionStorage.getItem(HISTORY_STORAGE_KEY);
        if (!raw) return { messages: [] };
        const parsed = JSON.parse(raw);
        if (parsed && Array.isArray(parsed.messages)) {
          return parsed;
        }
        return { messages: [] };
      } catch {
        return { messages: [] };
      }
    },
    async append(item) {
      try {
        const raw = sessionStorage.getItem(HISTORY_STORAGE_KEY);
        const repo =
          raw && JSON.parse(raw).messages
            ? JSON.parse(raw)
            : { messages: [] as Array<unknown> };
        repo.messages.push(item);
        sessionStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(repo));
      } catch (e) {
        console.warn('Failed to persist chat history:', e);
      }
    },
  };
}

/** SuggestionAdapter — fetches 3-4 follow-up question prompts from the
 * backend after each turn. Empty array on failure (don't surface a
 * spinner or error to the user; suggestions are nice-to-have). */
function createSuggestionAdapter() {
  return {
    async generate({ messages }: { messages: readonly ThreadMessage[] }) {
      // Empty thread — suggestions live in DefaultEmpty as static
      // starter prompts, no need to call the backend.
      if (messages.length === 0) return [];
      try {
        const payload = messages.map((m) => ({
          role: m.role === 'user' ? 'user' : 'assistant',
          content: extractMessageText(m),
        }));
        const response = await fetch('/api/chat/suggest', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ messages: payload }),
          credentials: 'include',
        });
        if (!response.ok) return [];
        const data = (await response.json()) as { suggestions?: { prompt: string }[] };
        return (data.suggestions ?? []).map((s) => ({ prompt: s.prompt }));
      } catch (err) {
        console.warn('Suggestion generation failed:', err);
        return [];
      }
    },
  };
}

export interface PhytoQueryRuntimeOptions {
  /** Returns the list of currently-selected source filenames. Called on
   * every send so the user's checkbox state always reflects in the
   * outgoing request without re-creating the adapter. */
  getSelectedFiles: () => string[];
  /** Initial messages to seed the thread with on first mount. Used for
   * "import paper from /search" handoff that pre-populates a question
   * about the imported PDF. */
  initialMessages?: readonly ThreadMessageLike[];
  /** When true, persists thread state to sessionStorage so it survives
   * a page reload within the same browser session. Default true. */
  enableSessionPersistence?: boolean;
}

export function usePhytoQueryRuntime(opts: PhytoQueryRuntimeOptions) {
  // Stash the latest getter in a ref so the adapter always reads the
  // current React state without being recreated on every render.
  const getSelectedFilesRef = useRef(opts.getSelectedFiles);
  getSelectedFilesRef.current = opts.getSelectedFiles;

  const adapter = useMemo<ChatModelAdapter>(
    () => ({
      // ChatModelAdapter.run can return either a Promise<ChatModelRunResult>
      // (one-shot) or an AsyncGenerator<ChatModelRunResult, void>
      // (streaming). We use the streaming form: yield a result for
      // every text delta so the UI paints progressively, then yield a
      // final result with the sources attached.
      async *run({ messages, abortSignal }): AsyncGenerator<ChatModelRunResult, void> {
        const lastUser = [...messages].reverse().find((m) => m.role === 'user');
        const question = lastUser ? extractMessageText(lastUser) : '';

        if (!question) {
          yield { content: [{ type: 'text', text: '' }] };
          return;
        }

        const chatHistory = toBackendChatHistory(messages);
        const selectedFiles = getSelectedFilesRef.current();

        // ── Streaming path ────────────────────────────────────────
        let streamResponse: Response | undefined;
        try {
          streamResponse = await openStream(
            question,
            selectedFiles,
            chatHistory,
            abortSignal,
          );
        } catch (err) {
          // Network/abort error before stream opened — fall through to
          // non-streaming path below (covers offline / DNS / aborts).
          if ((err as { name?: string })?.name === 'AbortError') throw err;
          streamResponse = undefined;
        }

        if (streamResponse && streamResponse.ok) {
          let accumulated = '';
          let sources: RagSource[] = [];
          let citations: Citation[] = [];
          let receivedAnyToken = false;
          let streamErrored = false;

          for await (const frame of readNdjsonFrames(streamResponse, abortSignal)) {
            if (frame.type === 'text_delta') {
              accumulated += frame.text;
              receivedAnyToken = true;
              // Re-yield with current sources/citations so the
              // MarkdownText preprocess can validate [chunk_id]
              // markers as text streams in (the backend now emits
              // the sources frame BEFORE text deltas).
              yield {
                content: [{ type: 'text', text: accumulated }],
                metadata: {
                  custom: { sources, citations } satisfies RagMessageCustomData,
                },
              };
            } else if (frame.type === 'sources') {
              sources = frame.sources;
              // Push the sources update into the message metadata
              // immediately — without this the frontend wouldn't see
              // the valid chunk_id set until the final yield, and
              // markers would render as literal text mid-stream.
              if (receivedAnyToken) {
                yield {
                  content: [{ type: 'text', text: accumulated }],
                  metadata: {
                    custom: { sources, citations } satisfies RagMessageCustomData,
                  },
                };
              }
            } else if (frame.type === 'citations') {
              citations = frame.citations;
            } else if (frame.type === 'answer_corrected') {
              // Reranker-driven re-attribution found at least one
              // [cN] marker the LLM cited that didn't match the
              // best-scoring chunk for the claim. Replace the
              // streamed text wholesale so subsequent renders use
              // the corrected chunk_id mappings. Visible superscript
              // numbers stay stable because Thread.tsx numbers
              // markers by order of first appearance — only the
              // underlying #cite-cN link target changes, so the
              // user doesn't see a flicker.
              accumulated = frame.text;
              yield {
                content: [{ type: 'text', text: accumulated }],
                metadata: {
                  custom: { sources, citations } satisfies RagMessageCustomData,
                },
              };
            } else if (frame.type === 'error') {
              streamErrored = true;
              throw new Error(frame.error || 'Stream error');
            } else if (frame.type === 'done') {
              break;
            }
          }

          if (!streamErrored && receivedAnyToken) {
            // Final yield carries sources + citations on the metadata.
            yield {
              content: [{ type: 'text', text: accumulated }],
              metadata: {
                custom: { sources, citations } satisfies RagMessageCustomData,
              },
            };
            return;
          }
          // No tokens received — fall through to JSON fallback.
        }

        // ── Non-streaming fallback ────────────────────────────────
        // Streaming endpoint returned non-OK or yielded no frames
        // (older backend, route not deployed, etc.) — fetch the full
        // answer in one shot from the existing JSON endpoint.
        const result = await postQuery(
          question,
          selectedFiles,
          chatHistory,
          abortSignal,
        );
        const sources = result.sources ?? [];
        yield {
          content: [{ type: 'text', text: result.answer ?? '' }],
          metadata: {
            custom: { sources } satisfies RagMessageCustomData,
          },
        };
      },
    }),
    [],
  );

  const history = useMemo<ThreadHistoryAdapter | undefined>(
    () =>
      opts.enableSessionPersistence === false
        ? undefined
        : createSessionHistoryAdapter(),
    [opts.enableSessionPersistence],
  );

  // Browser-builtin TTS for the ActionBar.Speak button. Class is
  // instantiated lazily so SSR (if ever) doesn't blow up on
  // window.speechSynthesis.
  const speech = useMemo(() => new WebSpeechSynthesisAdapter(), []);
  const suggestion = useMemo(() => createSuggestionAdapter(), []);

  return useLocalRuntime(adapter, {
    initialMessages: opts.initialMessages,
    adapters: {
      ...(history ? { history } : {}),
      speech,
      suggestion,
    },
  });
}

/** Public so the parent (RagPage's "Reset all" handler) can clear the
 * persisted chat history alongside the per-user RAG index. */
export function clearPersistedChatHistory(): void {
  try {
    sessionStorage.removeItem(HISTORY_STORAGE_KEY);
  } catch {
    /* noop */
  }
}
